# -*- coding: utf-8 -*-
"""standalone_trial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ySfIu63NiSuesSfd4A4T2c11KRSG800g
"""

#from google.colab import files
#img=files.upload()


import cv2
import numpy as np
import matplotlib.pyplot as plt


var=input('Press 1 to input a noisy image or press 2 to input synthetic image \t')
if(var)=='1':
	filename=input("Enter full path along with filename to read:")
elif(var)=='2':
	filename=input("Enter full path along with filename to read:")
else:
	print('Incorrect key; terminating')
	exit(0)



window_name='image'
img1 = cv2.imread(filename)
img=cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)

if(var=='2'):
	noise = img.copy()
	cv2.randn(noise, 0, 150)
	noisy=img + noise 


if(var=='1'):
	noisy=img

dend = cv2.fastNlMeansDenoising(noisy,None,50,7,21)


plt.imsave("denoised.png",dend)
plt.imsave("noisy.png",noisy)
print("Noisy and denoised images are saved")

print("\n PRESS ESC KEY TO TERMINATE")


cv2.imshow('image',img)
cv2.imshow('Noisy',noisy)
cv2.imshow('denoised',dend)
k=cv2.waitKey(0) & 0xFF
if k==27:
	cv2.destroyAllWindows()


